#
# copyright by Oliver Dippel o.dippel@gmx.de 2018
#

import os
import copy
import sys
import glob
import datetime
import time
import argparse
import json
import cv2
import PIL
from PIL import Image, ImageTk
import gi
gi.require_version('Gtk', '3.0') 
from gi.repository import Gtk, GdkPixbuf, Gdk, Pango, Gio, GObject
import cairo
import numpy as np
from io import StringIO

class VideoExport:
	def __init__(self, vi):
		self.vi = vi

	def kdenlive(self, path, project):
		output = open(path, "w")
		if output:
			output.write("<?xml version='1.0' encoding='utf-8'?>\n")
			output.write("<mlt title=\"Anonymous Submission\" version=\"6.6.0\" root=\"/tmp\" producer=\"main bin\" LC_NUMERIC=\"de_DE.UTF-8\">\n")
			output.write(" <profile width=\"1920\" frame_rate_den=\"1\" height=\"1080\" display_aspect_num=\"16\" display_aspect_den=\"9\" frame_rate_num=\"" + str(project["fps"]) + "\" colorspace=\"709\" sample_aspect_den=\"1\" description=\"HD 1080p " + str(project["fps"]) + " fps\" progressive=\"1\" sample_aspect_num=\"1\"/>\n")
			for fid in project["files"]:
				mov = project["files"][fid]
				output.write(" <producer id=\"" + str(mov["id"]) + "\" out=\"" + str(mov["frm_length"]) + "\" in=\"0\">\n")
				output.write("  <property name=\"length\">" + str(mov["frm_length"]) + "</property>\n")
				output.write("  <property name=\"eof\">pause</property>\n")
				output.write("  <property name=\"resource\">" + mov["path"] + "</property>\n")
				output.write("  <property name=\"seekable\">1</property>\n")
				output.write("  <property name=\"aspect_ratio\">1</property>\n")
				output.write("  <property name=\"audio_index\">1</property>\n")
				output.write("  <property name=\"video_index\">0</property>\n")
				output.write("  <property name=\"mute_on_pause\">1</property>\n")
				output.write("  <property name=\"kdenlive:folderid\">" + str(mov["trackid"]) + "</property>\n")
				output.write("  <property name=\"kdenlive:clipname\">" + mov["track"] + "-" + mov["name"] + "</property>\n")
				output.write("  <property name=\"kdenlive:description\">" + mov["camname"] + "\n" + mov["lens"] + "</property>\n")
				output.write(" </producer>\n")
			output.write(" <playlist id=\"main bin\">\n")
			for cid in project["tracks"]:
				cam = project["tracks"][cid]
				output.write("  <property name=\"kdenlive:folder.-1." + str(cam["id"]) + "\">" + str(cam["name"]) + "</property>\n")
			output.write("  <property name=\"kdenlive:docproperties.audiotargettrack\">2</property>\n")
			output.write("  <property name=\"kdenlive:docproperties.decimalPoint\">,</property>\n")
			output.write("  <property name=\"kdenlive:docproperties.dirtypreviewchunks\"/>\n")
			output.write("  <property name=\"kdenlive:docproperties.disablepreview\">0</property>\n")
			output.write("  <property name=\"kdenlive:docproperties.documentid\">1526288607975</property>\n")
			output.write("  <property name=\"kdenlive:docproperties.enableproxy\">0</property>\n")
			output.write("  <property name=\"kdenlive:docproperties.generateimageproxy\">0</property>\n")
			output.write("  <property name=\"kdenlive:docproperties.generateproxy\">0</property>\n")
			output.write("  <property name=\"kdenlive:docproperties.kdenliveversion\">17.12.3</property>\n")
			output.write("  <property name=\"kdenlive:docproperties.position\">0</property>\n")
			output.write("  <property name=\"kdenlive:docproperties.previewchunks\"/>\n")
			output.write("  <property name=\"kdenlive:docproperties.previewextension\"/>\n")
			output.write("  <property name=\"kdenlive:docproperties.previewparameters\"/>\n")
			output.write("  <property name=\"kdenlive:docproperties.profile\">atsc_1080p_" + str(project["fps"]) + "</property>\n")
			output.write("  <property name=\"kdenlive:docproperties.proxyextension\">mkv</property>\n")
			output.write("  <property name=\"kdenlive:docproperties.proxyimageminsize\">2000</property>\n")
			output.write("  <property name=\"kdenlive:docproperties.proxyminsize\">1000</property>\n")
			output.write("  <property name=\"kdenlive:docproperties.proxyparams\">-vf yadif,scale=960:-2 -qscale 3 -vcodec mjpeg -acodec pcm_s16le</property>\n")
			output.write("  <property name=\"kdenlive:docproperties.version\">0.96</property>\n")
			output.write("  <property name=\"kdenlive:docproperties.verticalzoom\">1</property>\n")
			output.write("  <property name=\"kdenlive:docproperties.videotargettrack\">3</property>\n")
			output.write("  <property name=\"kdenlive:docproperties.zonein\">0</property>\n")
			output.write("  <property name=\"kdenlive:docproperties.zoneout\">100</property>\n")
			output.write("  <property name=\"kdenlive:docproperties.zoom\">7</property>\n")
			output.write("  <property name=\"kdenlive:documentnotes\"/>\n")
			output.write("  <property name=\"kdenlive:clipgroups\"/>\n")
			output.write("  <property name=\"xml_retain\">1</property>\n")
			for fid in project["files"]:
				mov = project["files"][fid]
				output.write("  <entry out=\"" + str(mov["frm_length"]) + "\" producer=\"" + str(mov["id"]) + "\" in=\"0\"/>\n")
			output.write(" </playlist>\n")
			output.write(" <producer id=\"black\" out=\"500\" in=\"0\">\n")
			output.write("  <property name=\"length\">15000</property>\n")
			output.write("  <property name=\"eof\">pause</property>\n")
			output.write("  <property name=\"resource\">black</property>\n")
			output.write("  <property name=\"aspect_ratio\">0</property>\n")
			output.write("  <property name=\"mlt_service\">colour</property>\n")
			output.write("  <property name=\"set.test_audio\">0</property>\n")
			output.write(" </producer>\n")
			output.write(" <playlist id=\"black_track\">\n")
			output.write("  <entry out=\"1\" producer=\"black\" in=\"0\"/>\n")
			output.write(" </playlist>\n")
			for fid in project["files"]:
				mov = project["files"][fid]
				pid = str(mov["id"]) + "_playlist" + str(mov["trackid"])
				output.write(" <producer id=\"" + pid + "\" title=\"Anonymous Submission\" out=\"" + str(mov["frm_length"]) + "\" in=\"0\">\n")
				output.write("  <property name=\"length\">" + str(mov["frm_length"]) + "</property>\n")
				output.write("  <property name=\"eof\">pause</property>\n")
				output.write("  <property name=\"resource\">" + mov["path"] + "</property>\n")
				output.write("  <property name=\"audio_index\">1</property>\n")
				output.write("  <property name=\"video_index\">0</property>\n")
				output.write("  <property name=\"mute_on_pause\">1</property>\n")
				output.write("  <property name=\"mlt_service\">avformat-novalidate</property>\n")
				output.write("  <property name=\"seekable\">1</property>\n")
				output.write("  <property name=\"aspect_ratio\">1</property>\n")
				output.write("  <property name=\"kdenlive:folderid\">" + str(mov["trackid"]) + "</property>\n")
				output.write("  <property name=\"global_feed\">1</property>\n")
				output.write("  <property name=\"xml\">was here</property>\n")
				output.write("  <property name=\"meta.media.nb_streams\">3</property>\n")
				output.write("  <property name=\"meta.media.0.stream.type\">video</property>\n")
				output.write("  <property name=\"meta.media.0.stream.frame_rate\">" + str(mov["fps"]) + "</property>\n")
				output.write("  <property name=\"meta.media.0.stream.sample_aspect_ratio\">0</property>\n")
				output.write("  <property name=\"meta.media.0.codec.width\">1920</property>\n")
				output.write("  <property name=\"meta.media.0.codec.height\">1080</property>\n")
				output.write("  <property name=\"meta.media.0.codec.rotate\">0</property>\n")
				output.write("  <property name=\"meta.media.0.codec.frame_rate\">" + str(mov["fps"]) + "000</property>\n")
				output.write("  <property name=\"meta.media.0.codec.pix_fmt\">yuvj420p</property>\n")
				output.write("  <property name=\"meta.media.0.codec.sample_aspect_ratio\">1</property>\n")
				output.write("  <property name=\"meta.media.0.codec.colorspace\">709</property>\n")
				output.write("  <property name=\"meta.media.0.codec.color_trc\">1</property>\n")
				output.write("  <property name=\"meta.media.0.codec.name\">h264</property>\n")
				output.write("  <property name=\"meta.media.0.codec.long_name\">H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10</property>\n")
				output.write("  <property name=\"meta.media.0.codec.bit_rate\">28006267</property>\n")
				output.write("  <property name=\"meta.attr.0.stream.creation_time.markup\">2018-05-09T23:50:49.000000Z</property>\n")
				output.write("  <property name=\"meta.attr.0.stream.language.markup\">eng</property>\n")
				output.write("  <property name=\"meta.attr.0.stream.timecode.markup\">09:49:22:10</property>\n")
				output.write("  <property name=\"meta.attr.major_brand.markup\">qt  </property>\n")
				output.write("  <property name=\"meta.attr.minor_version.markup\">537331968</property>\n")
				output.write("  <property name=\"meta.attr.compatible_brands.markup\">qt  CAEP</property>\n")
				output.write("  <property name=\"meta.media.sample_aspect_num\">1</property>\n")
				output.write("  <property name=\"meta.media.sample_aspect_den\">1</property>\n")
				output.write("  <property name=\"meta.media.frame_rate_num\">" + str(mov["fps"]) + "</property>\n")
				output.write("  <property name=\"meta.media.frame_rate_den\">1</property>\n")
				output.write("  <property name=\"meta.media.colorspace\">709</property>\n")
				output.write("  <property name=\"meta.media.color_trc\">1</property>\n")
				output.write("  <property name=\"meta.media.width\">1920</property>\n")
				output.write("  <property name=\"meta.media.height\">1080</property>\n")
				output.write("  <property name=\"meta.media.top_field_first\">0</property>\n")
				output.write("  <property name=\"meta.media.progressive\">1</property>\n")
				output.write(" </producer>\n")
			for cid in project["tracks"]:
				cam = project["tracks"][cid]
				output.write(" <playlist id=\"playlist" + str(cam["id"]) + "\">\n")
				output.write("  <property name=\"kdenlive:track_name\">CAM: " + str(cam["name"]) + "</property>\n")
				last_frame = 0
				for fid in project["files"]:
					mov = project["files"][fid]
					if mov["trackid"] == cam["id"]:
						pid = str(mov["id"]) + "_playlist" + str(mov["trackid"])
						length = mov["duration"] * project["fps"]
						frm_begin = (mov["frm_begin"]) + project["tracks"][mov["trackid"]]["frm_trim"] + mov["frm_trim"]
						frm_end = frm_begin + length
						diff = frm_begin - last_frame
						output.write("  <blank length=\"" + str(int(diff)) + "\"/>\n")
						output.write("  <entry out=\"" + str(length) + "\" producer=\"" + pid + "\" in=\"0\"/>\n")
						last_frame = frm_end
				output.write(" </playlist>\n")
			output.write(" <tractor id=\"maintractor\" title=\"Anonymous Submission\" global_feed=\"1\" out=\"1\" in=\"0\">\n")
			output.write("  <track producer=\"black_track\"/>\n")
			for cid in project["tracks"]:
				cam = project["tracks"][cid]
				output.write("  <track producer=\"playlist" + str(cam["id"]) + "\"/>\n")
			output.write("  <transition id=\"transition0\">\n")
			output.write("   <property name=\"a_track\">0</property>\n")
			output.write("   <property name=\"b_track\">1</property>\n")
			output.write("   <property name=\"mlt_service\">mix</property>\n")
			output.write("   <property name=\"always_active\">1</property>\n")
			output.write("   <property name=\"sum\">1</property>\n")
			output.write("   <property name=\"internal_added\">237</property>\n")
			output.write("  </transition>\n")
			output.write("  <transition id=\"transition1\">\n")
			output.write("   <property name=\"a_track\">0</property>\n")
			output.write("   <property name=\"b_track\">2</property>\n")
			output.write("   <property name=\"mlt_service\">mix</property>\n")
			output.write("   <property name=\"always_active\">1</property>\n")
			output.write("   <property name=\"sum\">1</property>\n")
			output.write("   <property name=\"internal_added\">237</property>\n")
			output.write("  </transition>\n")
			output.write("  <transition id=\"transition2\">\n")
			output.write("   <property name=\"a_track\">0</property>\n")
			output.write("   <property name=\"b_track\">3</property>\n")
			output.write("   <property name=\"mlt_service\">mix</property>\n")
			output.write("   <property name=\"always_active\">1</property>\n")
			output.write("   <property name=\"sum\">1</property>\n")
			output.write("   <property name=\"internal_added\">237</property>\n")
			output.write("  </transition>\n")
			output.write("  <transition id=\"transition3\">\n")
			output.write("   <property name=\"a_track\">0</property>\n")
			output.write("   <property name=\"b_track\">3</property>\n")
			output.write("   <property name=\"compositing\">0</property>\n")
			output.write("   <property name=\"distort\">0</property>\n")
			output.write("   <property name=\"rotate_center\">0</property>\n")
			output.write("   <property name=\"mlt_service\">qtblend</property>\n")
			output.write("   <property name=\"internal_added\">237</property>\n")
			output.write("  </transition>\n")
			output.write("  <transition id=\"transition4\">\n")
			output.write("   <property name=\"a_track\">0</property>\n")
			output.write("   <property name=\"b_track\">4</property>\n")
			output.write("   <property name=\"mlt_service\">mix</property>\n")
			output.write("   <property name=\"always_active\">1</property>\n")
			output.write("   <property name=\"sum\">1</property>\n")
			output.write("   <property name=\"internal_added\">237</property>\n")
			output.write("  </transition>\n")
			output.write("  <transition id=\"transition5\">\n")
			output.write("   <property name=\"a_track\">0</property>\n")
			output.write("   <property name=\"b_track\">4</property>\n")
			output.write("   <property name=\"compositing\">0</property>\n")
			output.write("   <property name=\"distort\">0</property>\n")
			output.write("   <property name=\"rotate_center\">0</property>\n")
			output.write("   <property name=\"mlt_service\">qtblend</property>\n")
			output.write("   <property name=\"internal_added\">237</property>\n")
			output.write("  </transition>\n")
			output.write("  <transition id=\"transition6\">\n")
			output.write("   <property name=\"a_track\">0</property>\n")
			output.write("   <property name=\"b_track\">5</property>\n")
			output.write("   <property name=\"mlt_service\">mix</property>\n")
			output.write("   <property name=\"always_active\">1</property>\n")
			output.write("   <property name=\"sum\">1</property>\n")
			output.write("   <property name=\"internal_added\">237</property>\n")
			output.write("  </transition>\n")
			output.write("  <transition id=\"transition7\">\n")
			output.write("   <property name=\"a_track\">0</property>\n")
			output.write("   <property name=\"b_track\">5</property>\n")
			output.write("   <property name=\"compositing\">0</property>\n")
			output.write("   <property name=\"distort\">0</property>\n")
			output.write("   <property name=\"rotate_center\">0</property>\n")
			output.write("   <property name=\"mlt_service\">qtblend</property>\n")
			output.write("   <property name=\"internal_added\">237</property>\n")
			output.write("  </transition>\n")
			output.write(" </tractor>\n")
			output.write("</mlt>\n")
			output.close()

	def xmeml(self, path, project):
		output = open(path, "w")
		if output:
			output.write("<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n")
			output.write("<xmeml version=\"5\">\n")
			output.write("   <sequence id=\"E70B00O2\">\n")
			output.write("      <name>Sequence #1</name>\n")
			output.write("      <rate>\n")
			output.write("         <ntsc>FALSE</ntsc>\n")
			output.write("         <timebase>" + str(project["fps"]) + "</timebase>\n")
			output.write("      </rate>\n")
			output.write("      <timecode>\n")
			output.write("         <rate>\n")
			output.write("            <ntsc>FALSE</ntsc>\n")
			output.write("            <timebase>25</timebase>\n")
			output.write("         </rate>\n")
			output.write("         <string>00:00:00.00</string>\n")
			output.write("         <frame>0</frame>\n")
			output.write("         <source>source</source>\n")
			output.write("         <displayformat>NDF</displayformat>\n")
			output.write("      </timecode>\n")
			output.write("      <media>\n")
			output.write("         <format>\n")
			output.write("            <samplecharacteristics>\n")
			output.write("               <width>1920</width>\n")
			output.write("               <height>1080</height>\n")
			output.write("            </samplecharacteristics>\n")
			output.write("         </format>\n")
			output.write("         <video>\n")
			for cid in project["tracks"]:
				cam = project["tracks"][cid]
				output.write("            <track>\n")
				for fid in project["files"]:
					mov = project["files"][fid]
					if mov["trackid"] == cam["id"]:
						pid = str(mov["id"]) + "_playlist" + str(mov["trackid"])
						length = mov["frm_length"]
						frm_begin = (mov["frm_begin"]) + project["tracks"][mov["trackid"]]["frm_trim"] + mov["frm_trim"]
						frm_end = frm_begin + length
						output.write("               <clipitem>\n")
						output.write("                  <name>" + str(mov["name"]) + "</name>\n")
						output.write("                  <duration>" + str(length) + "</duration>\n")
						output.write("                  <rate>\n")
						output.write("                     <ntsc>FALSE</ntsc>\n")
						output.write("                     <timebase>" + str(mov["fps"]) + "</timebase>\n")
						output.write("                  </rate>\n")
						output.write("                  <in>0</in>\n")
						output.write("                  <out>" + str(length) + "</out>\n")
						output.write("                  <start>" + str(frm_begin) + "</start>\n")
						output.write("                  <end>" + str(frm_end) + "</end>\n")
						output.write("                  <masterclipid>" + str(cam["name"]) + "-" + str(mov["name"]) + "</masterclipid>\n")
						output.write("                  <file id=\"" + str(cam["name"]) + "-" + str(mov["name"]) + "\">\n")
						output.write("                     <name>" + str(mov["name"]) + "</name>\n")
						output.write("                     <pathurl>file://localhost/" + str(mov["path"]) + "</pathurl>\n")
						output.write("                     <rate>\n")
						output.write("                        <ntsc>FALSE</ntsc>\n")
						output.write("                        <timebase>" + str(mov["fps"]) + "</timebase>\n")
						output.write("                     </rate>\n")
						output.write("                     <duration>" + str(length) + "</duration>\n")
						output.write("                     <timecode>\n")
						output.write("                        <rate>\n")
						output.write("                           <ntsc>FALSE</ntsc>\n")
						output.write("                           <timebase>" + str(mov["fps"]) + "</timebase>\n")
						output.write("                        </rate>\n")
						output.write("                        <string>00:00:00.00</string>\n")
						output.write("                        <frame>0</frame>\n")
						output.write("                        <source>source</source>\n")
						output.write("                        <displayformat>NDF</displayformat>\n")
						output.write("                        <reel>\n")
						output.write("                           <name>" + str(mov["name"]) + "</name>\n")
						output.write("                        </reel>\n")
						output.write("                     </timecode>\n")
						output.write("                     <media>\n")
						output.write("                        <video>\n")
						output.write("                           <duration>" + str(length) + "</duration>\n")
						output.write("                           <samplecharacteristics>\n")
						output.write("                              <width>1920</width>\n")
						output.write("                              <height>1080</height>\n")
						output.write("                           </samplecharacteristics>\n")
						output.write("                        </video>\n")
						output.write("                        <audio>\n")
						output.write("                           <channelcount>2</channelcount>\n")
						output.write("                        </audio>\n")
						output.write("                     </media>\n")
						output.write("                  </file>\n")
						output.write("                  <sourcetrack>\n")
						output.write("                     <mediatype>video</mediatype>\n")
						output.write("                  </sourcetrack>\n")
						output.write("               </clipitem>\n")
				output.write("            </track>\n")
			output.write("         </video>\n")
			output.write("         <audio>\n")
			output.write("         </audio>\n")
			output.write("      </media>\n")
			output.write("   </sequence>\n")
			output.write("</xmeml>\n")

